language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
before_script:
  - "wget https://github.com/google/cayley/releases/download/v0.4.1/cayley_0.4.1_linux_amd64.tar.gz"
  - "tar -xvzf cayley_0.4.1_linux_amd64.tar.gz"
  - "./cayley_0.4.1_linux_amd64/cayley http --dbpath=data/testdata.nq &"
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
script: py.test tests
